### ISSUE TITLE
Can't load if I use more than 12 plugins.

### ISSUE THREAD

**Issue by JoeCow** [Krglok/Realms#59]
I really like the idea of this plugin but if I try to load more than 12 plugins realms will not load. I tried with a bunch of different plugin combinations thinking there was some kind of plugin conflict but the only thing I could do to get it to work was use 12 or less plugins. Anytime I would use 13 it would no longer work. Let me know if you need any other details.
```
[22:18:43] [Server thread/ERROR]: Could not load 'plugins\Realms.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/aufdemrand/sentry/SentryTrait
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NoClassDefFoundError: net/aufdemrand/sentry/SentryTrait
	at net.krglok.realms.Realms.<init>(Realms.java:116) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_31]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.sentry.SentryTrait
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at net.krglok.realms.Realms.<init>(Realms.java:116) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_31]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	... 6 more
```

**Comment by Krglok** [comment]
Hello, good morning,

 

Caused by: java.lang.NoClassDefFoundError: net/aufdemrand/sentry/SentryTrait

 

You need the sentry plugin to install. When you have installed citizens. 

When not installed citizens, then please reply, then its an error .

 

Krglok

Ruler of Draskoria.net Minecraft

 

 

 

Von: JoeCow [mailto:notifications@github.com] 
Gesendet: Freitag, 27. Februar 2015 04:28
An: Krglok/Realms
Betreff: [Realms] Can't load if I use more than 12 plugins. (#59)

 

I really like the idea of this plugin but if I try to load more than 12 plugins realms will not load. I tried with a bunch of different plugin combinations thinking there was some kind of plugin conflict but the only thing I could do to get it to work was use 12 or less plugins. Anytime I would use 13 it would no longer work. Let me know if you need any other details.

[22:18:43] [Server thread/ERROR]: Could not load 'plugins\Realms.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/aufdemrand/sentry/SentryTrait
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NoClassDefFoundError: net/aufdemrand/sentry/SentryTrait
    at net.krglok.realms.Realms.<init>(Realms.java:116) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_31]
    at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_31]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.sentry.SentryTrait
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_31]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
    at net.krglok.realms.Realms.<init>(Realms.java:116) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_31]
    at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_31]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    ... 6 more

**Comment by JoeCow** [comment]
I had sentry and citizens installed when I was testing that. It would work fine when I had 12 plugins or less but as soon as I would hit 13 or more it would no longer find sentry.

**Comment by Krglok** [comment]
Ok, i make a test and look at the source of issue Position
In my Server Installation are 20 plugins, so it cannot be the number of plugins.

**Comment by Krglok** [comment]
The plugin.yml has no depends: Sentry
I think this is the error cause

**Comment by Krglok** [comment]
Hello agian,

Can you give me a list of your plugins you installed on your server.

I cannot reproduce the error . So I cannot verify the a fixe.

 

Thank you,

Krglok

 

Von: JoeCow [mailto:notifications@github.com] 
Gesendet: Freitag, 27. Februar 2015 04:28
An: Krglok/Realms
Betreff: [Realms] Can't load if I use more than 12 plugins. (#59)

 

I really like the idea of this plugin but if I try to load more than 12 plugins realms will not load. I tried with a bunch of different plugin combinations thinking there was some kind of plugin conflict but the only thing I could do to get it to work was use 12 or less plugins. Anytime I would use 13 it would no longer work. Let me know if you need any other details.

[22:18:43] [Server thread/ERROR]: Could not load 'plugins\Realms.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/aufdemrand/sentry/SentryTrait
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NoClassDefFoundError: net/aufdemrand/sentry/SentryTrait
    at net.krglok.realms.Realms.<init>(Realms.java:116) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_31]
    at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_31]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.sentry.SentryTrait
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_31]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
    at net.krglok.realms.Realms.<init>(Realms.java:116) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_31]
    at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_31]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
    ... 6 more

**Comment by JoeCow** [comment]
I did a clean install and it still happens on both my debian server and my local windows machine as soon as I get over 12 plugins regardless of what plugins I use. Maybe I am doing something wrong. Should I be using the latest dev build of sentry and citizens or the latest version on bukkit?

**Comment by Krglok** [comment]
hmm.. what machine yo have ?  I think you need 3-4 GB  RAM for the server. depends on your world and the plugins.  Have you set the ram parameter for startup ?
This my old debian start : 
java -d64 -Xms1500M -Xmx4500M -jar craftbukkit.jar

has mulitple worlds and  a large world of 20000x20000 blocks 
upto 32 plugins

when you start the server on windows you should use BukkitGUI.exe. This is a bukkit project and you can download it from bukkitdev

**Comment by JoeCow** [comment]
Hmmm tried -xmx10000M and still no good. I'll just put it on it's own server for now with bungee.
