### ISSUE TITLE
Cild birth exception

### ISSUE THREAD

**Issue by Krglok** [Krglok/Realms#75]
14:07:16 [INFO] [REALMS] childbirth  342
14:07:16 [INFO] [REALMS] New Child 1 born living as BEGGAR
14:07:16 [INFO] [Realms] ERROR exception null
14:07:16 [INFO] java.util.ConcurrentModificationException
14:07:16 [INFO] 	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
14:07:16 [INFO] 	at java.util.HashMap$ValueIterator.next(HashMap.java:835)
14:07:16 [INFO] 	at net.krglok.realms.core.Resident.doLifeCycle(Resident.java:516)
14:07:16 [INFO] 	at net.krglok.realms.core.Resident.doSettlerCalculation(Resident.java:736)
14:07:17 [INFO] 	at net.krglok.realms.core.AbstractSettle.doHappiness(AbstractSettle.java:524)
14:07:17 [INFO] 	at net.krglok.realms.model.RealmModel.nextProductionQueue(RealmModel.java:886)
14:07:17 [INFO] 	at net.krglok.realms.model.RealmModel.OnTick(RealmModel.java:560)
14:07:17 [INFO] 	at net.krglok.realms.TickTask.run(TickTask.java:128)
14:07:17 [INFO] 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
14:07:17 [INFO] 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
14:07:17 [INFO] 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:653)
14:07:17 [INFO] 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
14:07:17 [INFO] 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598)
14:07:17 [INFO] 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506)
14:07:17 [INFO] 	at java.lang.Thread.run(Thread.java:722)
14:07:17 [INFO] [Realms] Model Disabled !

**Comment by Krglok** [comment]
Eien seoparate Liste wirde verwendet zum inetrieren
